Instance created. Preparing to start...
Image download failure. Image does not exist. Please check your Service configuration.
Instance created. Preparing to start...
Instance stopped.
Image download failure. Image does not exist. Please check your Service configuration.
Instance stopped.
